import torch
import torch_npu
from torch.contrib import transfer_to_npu
import adaptor_moe_shared_moe
import adaptor_pipe_engine
import adaptor_pipe_module
import adaptor_runtime_comm_coalesced_collectives
import adaptor_runtime_fp16_fused_optimizer
import adaptor_runtime_fp16_loss_scaler
import adaptor_runtime_fp16_unfused_optimizer
import adaptor_utils_nvtx
import adaptor_zero_partition_parameters
import adaptor_zero_stage_1_and_2
import adaptor_zero_stage3